{
 "title": "fastn_dashbord_2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"samurai-controlplane\"} |= `copilot`"
    }
   ]
  },
  {
   "title": "fastn Auth Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apis_users_unauthorized_seconds_count{clientId=\"knexa\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(graphql_errors_seconds_count{code=\"INTERNAL_SERVER_ERROR\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not found Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(graphql_errors_seconds_count{code=\"RESOURCE_NOT_FOUND\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logged Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(logback_events_total{level=\"error\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logged Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(logback_events_total{level=\"warn\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customers  APIs Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apis_requests_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customers success request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apis_requests_seconds_count{status=\"success\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customers APIs Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apis_requests_seconds_count{status=\"error\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customers Auth Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apis_users_unauthorized_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(copilotApp_logs_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keycloak total request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(operation_keycloak_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "customers APIs requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(apis_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max  Latency",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(graphql_server_requests_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(graphql_server_requests_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(graphql_server_requests_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(graphql_server_requests_seconds_count{status=\"success\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Error Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(graphql_server_requests_seconds_count{status=\"error\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(graphql_errors_seconds_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(graphql_errors_seconds_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max DB latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(operation_db_seconds_max[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fastn requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_server_requests_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max DB latency per query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(query) (increase(operation_db_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keycloak requests per query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(query) (increase(operation_keycloak_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Keycloak latency by query",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(query) (increase(operation_keycloak_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max fastn latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(apis_requests_seconds_max[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Project",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_server_requests_seconds_count{operation=\"getOrganization\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Keycloak latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(operation_keycloak_seconds_max[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List Projects query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_server_requests_seconds_count{operation=\"getOrganizations\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Projects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(graphql_server_requests_seconds_count{operation=\"addOrganization\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}